# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='relevemeteo',
            index=models.Index(fields=['ville', 'date'], name='meteo_ville_date_idx'),
        ),
        migrations.AddIndex(
            model_name='relevemeteo',
            index=models.Index(fields=['date'], name='meteo_date_idx'),
        ),
    ]
