# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alerte_options_alerte_date_publication_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['statut'], name='alerts_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['est_active'], name='alerts_est_active_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['ville', 'statut'], name='alerts_ville_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['date_creation'], name='alerts_date_creation_idx'),
        ),
    ]
