# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qualiteair',
            index=models.Index(fields=['ville', 'date_cible'], name='air_quality_ville_i_idx'),
        ),
        migrations.AddIndex(
            model_name='qualiteair',
            index=models.Index(fields=['date_cible'], name='air_quality_date_ci_idx'),
        ),
        migrations.AddIndex(
            model_name='qualiteair',
            index=models.Index(fields=['est_prediction'], name='air_quality_est_pre_idx'),
        ),
        migrations.AddIndex(
            model_name='qualiteair',
            index=models.Index(fields=['categorie'], name='air_quality_categor_idx'),
        ),
    ]
